<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:20;}
.tg td{border-color:black;border-style:solid;border-width:2px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:20px 20px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:15px 15px;word-break:normal;}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>

<div class="container">
  
    La società Bianchi & Partners nasce nel 1995 a Praga su iniziativa dei soci del Gruppo Dracma, con l’obiettivo di prestare attività di consulenza ed assistenza aziendale, tributaria, societaria, del lavoro, legale, fiscale e di supporto agli investitori italiani, con particolare attenzione a quelli stranieri, in Repubblica Ceca. L’imprenditore ha bisogno di trovare i giusti riferimenti per sviluppare la propria attività, di individuare i partner giusti ed i canali per sviluppare contatti con aziende locali; di essere assistito nella scelta dei rappresentanti o dei fornitori; di reperire interpreti e consulenti qualificati e professionali; ma soprattutto, ha bisogno di qualcuno che capisca ciò di cui ha bisogno e lo introduca nel mercato, nella cultura, nella società del Paese. Potremmo sintetizzare così: per far crescere la sua attività all’estero, l’imprenditore ha bisogno di un angolo d’Italia nel Paese in cui si trova. Un angolo familiare, abitato da persone che pensano da italiani, che conoscono le esigenze dell’imprenditore italiano, ma allo stesso tempo sono perfettamente inseriti nell’ambiente del Paese che li ospita, ne conoscono la mentalità e le opportunità, le leggi e le tradizioni. E che quindi possano fare da ponte tra le due realtà. La società Bianchi & Partners è costituita da un nucleo di valenti professionisti con concrete esperienze, soprattutto a livello internazionale, con un’ampia conoscenza del paese dove operano e perciò in grado di poter offrire il più valido ed efficiente aiuto sia agli operatori economici che vogliono per la prima volta affrontare un nuovo mercato, sia a coloro che sono già in esso presenti. Lo studio si avvale di personale bilingue con una stimata e profonda esperienza nei vari settori; è in continuo aggiornamento sia sulle problematiche tecniche che organizzative per offrire soluzioni operative ed efficaci ad ogni singola esigenza.
</div>